
SMTP_SERVER: smtp.gmail.com
SMTP_PORT: 587 
GMAIL_USERNAME: noreply.starryeyes@gmail.com
GMAIL_PASSWORD: dgur tkpe lolq kdlq

fredi_email: fredrik.lennstroem@students.fhnw.ch
silas_email: silas.haab@students.fhnw.ch
alex_email: alex.bura@students.fhnw.ch

